var rawDataProjects = [
  {
    title:       'Street Fighter GAme',
    category:    'games',
    institute:   'Coding Dojo',
    instituteUrl:'http://www.codingdojo.com/',
    // publishedOn: '2015-10-28',
    // body:        '<p>Freegan put a bird on it narwhal, umami marfa viral you probably haven\'t heard of them four loko kinfolk YOLO celiac echo park. <img src="http://lorempixel.com/400/300/nightlife/" class="pull-left">Viral synth fanny pack taxidermy, portland crucifix pug intelligentsia helvetica slow-carb. Venmo synth migas paleo salvia fingerstache retro, microdosing green juice pug taxidermy. Helvetica disrupt cliche you probably haven\'t heard of them mustache brooklyn. Artisan gentrify austin, hoodie portland retro yr fashion axe heirloom lumbersexual tacos messenger bag. Austin hella four loko everyday carry portland synth. Flexitarian schlitz migas yr pitchfork iPhone.</p><p>Deep v mlkshk helvetica austin PBR&B lomo raw denim blue bottle VHS cliche street art. Thundercats biodiesel craft beer cronut disrupt, tattooed ennui scenester chia deep v. Tofu +1 roof party, craft beer chicharrones ramps ugh iPhone mixtape. Vice 3 wolf moon farm-to-table chia before they sold out hammock chillwave. Deep v stumptown actually helvetica normcore chambray. Banjo scenester mumblecore gastropub church-key. Austin craft beer beard locavore wolf.</p><p>Hashtag try-hard chartreuse selvage, readymade mustache tote bag stumptown. Letterpress 3 wolf moon waistcoat small batch. Single-origin coffee williamsburg church-key, truffaut tacos yuccie stumptown synth waistcoat literally you probably haven\'t heard of them ennui. Narwhal everyday carry cardigan, vegan microdosing pitchfork flannel lomo deep v kombucha shabby chic poutine. Williamsburg VHS squid, mlkshk you probably haven\'t heard of them franzen small batch photo booth taxidermy meggings. Small batch sustainable tousled, hashtag flannel cornhole locavore polaroid lo-fi salvia helvetica franzen austin. Fixie disrupt polaroid, raw denim readymade green juice deep v scenester dreamcatcher tumblr.</p><p>Intelligentsia cray blue bottle, cardigan pinterest biodiesel ethical polaroid 8-bit master cleanse. Fap direct trade locavore, ethical shoreditch everyday carry kombucha poutine kickstarter austin. Plaid photo booth knausgaard helvetica, skateboard beard intelligentsia kitsch mixtape. Next level kinfolk farm-to-table semiotics, umami meh quinoa. Listicle viral selfies, street art kombucha squid fanny pack. Artisan XOXO heirloom, everyday carry bicycle rights lumbersexual beard roof party tattooed paleo kitsch fingerstache gluten-free. Cronut YOLO blue bottle meh, banjo skateboard vinyl austin aesthetic put a bird on it chicharrones you probably haven\'t heard of them etsy venmo direct trade.</p>'
    body:'<iframe src="https://arora26shruti.github.io/Street-Fighter-Game/" width="660" height="263" seamless="seeamless" style="overflow: hidden;overflow-y: hidden; background-color: white;" scrolling="no"></iframe><br> Description- A basic code was discussed in the class-its functionality, Concepts etc. We were supposed to add new movements and features like double kick and fire effects, to the two Players with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.<hr></p>'
  },
  {
    title:       '<h5>Responsive Website</h5>',
    category:    'websites',
    institute:   'Amity University,Noida',
    instituteUrl:   'http://www.amity.edu/index.aspx',
    // publishedOn: '2015-11-04',
    body: '<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.<hr></p>'
  // body:        '<p>Baseball ipsum dolor sit amet base on balls full count leadoff. National pastime stance pine tar dribbler rookie dodgers hardball plate. <img src="http://lorempixel.com/400/200/" class="pull-left" >Club sidearm shift red sox ground rule double, left fielder pennant good eye rubber game. Steal petey center field blue wins arm visitors. Out rope base cookie grass bandbox error. Tag pennant designated hitter relief pitcher triple-A alley on deck baseball.</p><p>Dribbler left on base arm curve bag, slider around the horn disabled list. Pennant catcher gapper rope screwball home cork foul. Nubber slide rake relief pitcher wrigley choke up cup of coffee cycle bench. Loss strikeout bandbox cardinals second base practice gap center fielder. Screwball fielder\'s choice play baseline rubber game warning track bleeder. Mustard inning in the hole astroturf alley fielder\'s choice left fielder.</p><p>Home grand slam suicide squeeze breaking ball batter\'s box flyout starting pitcher. Baseball card basehit double switch save batting average losses tossed umpire batter\'s box. Shift league 4-6-3 no-hitter yankees, bleeder mound defensive indifference shutout. Squeeze mound butcher boy loss rip chin music cracker jack. Scorecard all-star helmet practice defensive indifference pull mound around the horn. Earned run relay curve full count fall classic pinch hitter helmet cheese outfielder.</p><p>Foul pitchout moneyball all-star runs left on base fielder\'s choice. Sport pine tar fair dead ball era season rip no-hitter friendly confines. Baseball card no-hitter fenway line drive left field earned run sport bush league. Tossed walk off dodgers error streak, center fielder tossed chin music. Grounder friendly confines mustard center field bandbox pinch runner cookie. Alley left on base bat second baseman passed ball foul error cy young.</p><p>No-hitter breaking ball stadium doubleheader rubber fair team rake. Error leather left fielder outs at-bat leadoff cork hit by pitch rally. Relief pitcher bleeder sidearm grounder center fielder gold glove ejection hitter foul line. Error 4-6-3 gold glove knuckleball dead ball era, save pine tar. Robbed reliever cellar alley stretch club starter leather. Red sox dead red pull no-hitter assist can of corn manager error play.</p>'
  },

];
